log using c:\wodon\bhesdata\log\scr192b, replace
infile using c:\wodon\bhesdata\scr192b

label define S192COL3 003 "Crops; Rice                gr"
label define S192COL3 004 "Wheat & Wheat flour        gr", add
label define S192COL3 005 "Beaten rice / Fried rice  gr", add
label define S192COL3 006 "Vermicellie / Suji         gr", add
label define S192COL3 007 "Bread / Bonruti            gr", add
label define S192COL3 008 "Biscuit / Cake             gr", add
label define S192COL3 009 "Others (Crops)             gr", add
label define S192COL3 020 "Pulses : Lentil            gr", add
label define S192COL3 021 "Chickling-Vetch            gr", add
label define S192COL3 022 "Green gram                 gr", add
label define S192COL3 023 "Pea / gram                 gr", add
label define S192COL3 024 "Others (Pulses)            gr", add
label define S192COL3 028 "Fish; Hilsa                gr", add
label define S192COL3 029 "Kai/Magur/Shingi/Khalisha  gr", add
label define S192COL3 030 "Shoal/Gazar/Taki           gr", add
label define S192COL3 031 "Punti/Big-Punti            gr", add
label define S192COL3 032 "Mala-Kachki/Chala-Chapila  gr", add
label define S192COL3 033 "Shrimp fish                gr", add
label define S192COL3 034 "Dried fish                 gr", add
label define S192COL3 035 "Tangra/Elfish              gr", add
label define S192COL3 036 "Sea fish                   gr", add
label define S192COL3 037 "Others (Fish)              gr", add
label define S192COL3 065 "Hen egg                    No", add
label define S192COL3 066 "Duck egg                   No", add
label define S192COL3 067 "Others (Egg)               No", add
label define S192COL3 069 "Meet;Beef/Buffalo          gr", add
label define S192COL3 070 "Mutton/Sheep               gr", add
label define S192COL3 071 "Duck/Hen                   gr", add
label define S192COL3 072 "Others (Meet)              gr", add
label define S192COL3 077 "Vegetables;Potato          gr", add
label define S192COL3 078 "Brinjal                    gr", add
label define S192COL3 079 "White gourd/Pumpkin        gr", add
label define S192COL3 080 "Water gourd                gr", add
label define S192COL3 081 "Balsam apple               gr", add
label define S192COL3 082 "Perbol                     gr", add
label define S192COL3 083 "Snake gourd/Ribbed gourd   gr", add
label define S192COL3 084 "Green Banana               gr", add
label define S192COL3 085 "Arum/Galkachu/Kachur-muki  gr", add
label define S192COL3 086 "Cauliflower/Cabbage        gr", add
label define S192COL3 087 "Bean/Lobey                 gr", add
label define S192COL3 088 "Tomato                     gr", add
label define S192COL3 089 "Ladies finger              gr", add
label define S192COL3 090 "Others (Vegetables)        gr", add
label define S192COL3 110 "Veg/Spinach/Amaranta       gr", add
label define S192COL3 111 "Others (Sak)               gr", add
label define S192COL3 125 "Milk & Milk products       ml", add
label define S192COL3 126 "Powder Milk                gr", add
label define S192COL3 127 "Curd/Ponir/Butter          gr", add
label define S192COL3 128 "Drinks of Milk             gr", add
label define S192COL3 129 "Others (Milk)              gr", add
label define S192COL3 130 "Sweetmeat;Rasogolla/chamchagr", add
label define S192COL3 131 "Jilapi/Bundia/Amriti       gr", add
label define S192COL3 132 "Halua/Batasha/Kadma        gr", add
label define S192COL3 133 "Others (Sweet)             gr", add
label define S192COL3 135 "Oil & Fats;Mustard oil     gr", add
label define S192COL3 136 "Soyabean oil               ml", add
label define S192COL3 137 "Dalda/Ghee/Vanaspati       ml", add
label define S192COL3 138 "Others (Oil)               ml", add
label define S192COL3 140 "Spices; Green chili        gr", add
label define S192COL3 141 "Dried Chili                gr", add
label define S192COL3 142 "Onion                      gr", add
label define S192COL3 143 "Garlic                     gr", add
label define S192COL3 144 "Turmeric                   gr", add
label define S192COL3 145 "Salt                       gr", add
label define S192COL3 146 "Others (Spices)            gr", add
label define S192COL3 155 "Fruits; Banana             gr", add
label define S192COL3 156 "Mango                      gr", add
label define S192COL3 157 "Jack fruit                 gr", add
label define S192COL3 158 "Leechee                    gr", add
label define S192COL3 159 "Ripe Papya                 gr", add
label define S192COL3 160 "Guava                      gr", add
label define S192COL3 161 "Pineapple                  gr", add
label define S192COL3 162 "Others (Fruits)            gr", add
label define S192COL3 180 "Drinks; Fanta/C.cola/Soda  No", add
label define S192COL3 181 "Ovaltine/Horlicks          gr", add
label define S192COL3 182 "Tea/Coffee                cup", add
label define S192COL3 183 "Others (Drinks)           cup", add
label define S192COL3 187 "Sugar & Molasses; Sugar    gr", add
label define S192COL3 188 "Molasses(sugar cane,dat etcgr", add
label define S192COL3 189 "Khaja/Logence/Chocolate/TafNo", add
label define S192COL3 190 "Others (Sugar)             No", add
label define S192COL3 192 "Betalleaf & Chewgoods b.leaNo", add
label define S192COL3 193 "Betalnut                   gr", add
label define S192COL3 194 "Zorda/Tobacco leaf         gr", add
label define S192COL3 195 "Prepared Betalleaf         No", add
label define S192COL3 196 "Others (Chewgoods)         No", add
label define S192COL3 200 "Misc.Food;Pickles          gr", add
label define S192COL3 201 "Jelly/Circa                gr", add
label define S192COL3 202 "Amsatta                    gr", add
label define S192COL3 203 "Others (Misc.)             gr", add
label define S192COL3 210 "Dine-out expenses; Rice-cur  ", add
label define S192COL3 211 "Sweetmeat(Specify)           ", add
label define S192COL3 212 "Others (Specify)             ", add
label define S192COL3 220 "Biri/Cigarette             No", add
label define S192COL3 221 "Tobacco Huka               gr", add
label define S192COL3 222 "Tobacco Leaf               gr", add
label define S192COL3 223 "Others (Tobacco)             ", add
label define S192COL3 225 "Other expenses;Travelling    ", add
label define S192COL3 226 "Children pocket expenses     ", add
label define S192COL3 227 "Others (Other.)              ", add
label values S192COL3 S192COL3
label define S192COL7 1 "Bought "
label define S192COL7 2 "Home Made", add
label define S192COL7 3 "Gift ", add
label values S192COL7 S192COL7

gen dec = S192COLB / 100
replace dec = 0 if dec==.
drop S192COLB
replace S192COL6 = S192COL6+dec
drop dec

save c:\wodon\bhesdata\Z192, replace
summarize
log close
clear

